/**
 * Build-time generator for `server/_generated/buildInfo.ts`.
 *
 * Pulls `version` from `package.json`, then runs `git rev-list --count HEAD`
 * and `git rev-parse --short HEAD` to compose a `BuildInfo` value, and writes
 * a tiny TypeScript module under `server/_generated/` (optional local metadata).
 * Production deploy version strings for operators come from `build-info.json`
 * at the repo root (written by `deploy.sh`), read only via `platform.runtimeInfo`.
 *
 * Designed to be robust to missing git / shallow clones — falls back to safe
 * placeholder values so the build never fails because of metadata collection.
 *
 * Run via `pnpm build` (prepended in `package.json`) or directly:
 *   tsx scripts/generate-build-info.ts
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { composeBuildInfo, type BuildInfo } from "../server/_core/buildInfoCompose";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const PACKAGE_JSON_PATH = resolve(REPO_ROOT, "package.json");
const OUTPUT_PATH = resolve(REPO_ROOT, "server/_generated/buildInfo.ts");

function readPackageVersion(): string | null {
  try {
    const raw = readFileSync(PACKAGE_JSON_PATH, "utf8");
    const parsed = JSON.parse(raw) as { version?: unknown };
    return typeof parsed.version === "string" ? parsed.version : null;
  } catch {
    return null;
  }
}

function runGit(args: string[]): string | null {
  try {
    return execFileSync("git", args, {
      cwd: REPO_ROOT,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
      timeout: 5_000,
    }).trim();
  } catch {
    return null;
  }
}

function readCommitCount(): number | null {
  const out = runGit(["rev-list", "--count", "HEAD"]);
  if (out == null) return null;
  const n = Number.parseInt(out, 10);
  return Number.isFinite(n) && n >= 0 ? n : null;
}

function readCommitSha(): string | null {
  const out = runGit(["rev-parse", "--short", "HEAD"]);
  return out && out.length > 0 ? out : null;
}

function renderTsModule(info: BuildInfo): string {
  // `JSON.stringify` produces a value-only literal — no expressions, no
  // template strings, so there is no place for a secret to be interpolated.
  const obj = JSON.stringify(info, null, 2);
  return `// AUTO-GENERATED — do not edit by hand.
// Regenerated by \`scripts/generate-build-info.ts\` during \`pnpm build\`.
// The committed copy is a safe placeholder used by \`pnpm check\` / \`pnpm test\`
// on fresh clones; \`pnpm build\` overwrites it with values from the local
// git repo. No secrets are written to this file.

import type { BuildInfo } from "../_core/buildInfoCompose";

export const BUILD_INFO: BuildInfo = ${obj};
`;
}

function main(): void {
  const info = composeBuildInfo({
    packageVersion: readPackageVersion(),
    commitCount: readCommitCount(),
    commitSha: readCommitSha(),
    now: new Date(),
  });
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, renderTsModule(info), "utf8");
  // eslint-disable-next-line no-console -- this is a build-time CLI.
  console.log(
    `[build-info] Wrote ${OUTPUT_PATH} (version=${info.version} commit=${info.commit ?? "null"} count=${
      info.commitCount ?? "null"
    })`,
  );
}

try {
  main();
} catch (err) {
  // Never block a build for telemetry; leave the committed placeholder.
  // eslint-disable-next-line no-console -- this is a build-time CLI.
  console.warn(
    "[build-info] Generation failed; placeholder kept:",
    err instanceof Error ? err.message : String(err),
  );
  process.exit(0);
}
