// AUTO-GENERATED — do not edit by hand.
// Regenerated by `scripts/generate-build-info.ts` during `pnpm build`.
// The committed copy is a safe placeholder used by `pnpm check` / `pnpm test`
// on fresh clones; `pnpm build` overwrites it with values from the local
// git repo. No secrets are written to this file.

import type { BuildInfo } from "../_core/buildInfoCompose";

export const BUILD_INFO: BuildInfo = {
  "version": "v1.0.119",
  "commit": "2089ad1",
  "buildTime": "2026-05-14T10:34:44.875Z",
  "commitCount": 119
};
